server:
  servlet:
    context-path: /good
  port: 8084

filter:
  paths:
#    - /login
#    - /logout
    - /*

spring:
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  #resources:
  #add-mappings: false #不要为资源文件建立映射

  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:8081/trading?characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: 1234
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  servlet:
    multipart:
      enabled: true
      max-file-size: -1  #单个文件的最大上限(b),负数为不限
      max-request-size: -1 #单次请求的文件总大小上限(b),负数为不限

mybatis:
  #mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.demo.good.entity
  #开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

